### ISSUE TITLE
about the paper

### ISSUE THREAD

**Issue by CHNtao** [YLab-UChicago/Memristor-Spikelearn#1]
hi, this is a excellent research, but i wanna know where can i get  access to your paper, when i search in google scholar found none of them matched.

**Comment by yanjingl** [comment]
This paper is published in DATE this year (https://www.date-conference.com/date-2023-accepted-papers) and should be available on IEEE soon. Here is a public version of the paper: https://drive.google.com/file/d/1rGOHfNlun-So5k6WMwRH_893xiZRi-Ya/view

**Comment by CHNtao** [comment]
Thank you for your prompt response.
